// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/operation-group":{"path":"components/operation-group","id":"docs/components/operation-group","parentId":"DocLayout"},"docs/components/search-table":{"path":"components/search-table","id":"docs/components/search-table","parentId":"DocLayout"},"docs/components/pro-table":{"path":"components/pro-table","id":"docs/components/pro-table","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/search-form-v2/README":{"id":"components/search-form-v2/README","path":"components/search-form-v2","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/hulongchao/Documents/code/2026/vite-playground/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/hulongchao/Documents/code/2026/vite-playground/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/hulongchao/Documents/code/2026/vite-playground/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/operation-group': React.lazy(() => import(/* webpackChunkName: "docs__components__operation-group.md" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/operation-group.md')),
'docs/components/search-table': React.lazy(() => import(/* webpackChunkName: "docs__components__search-table.md" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/search-table.md')),
'docs/components/pro-table': React.lazy(() => import(/* webpackChunkName: "docs__components__pro-table.md" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/pro-table.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/index.md')),
'components/search-form-v2/README': React.lazy(() => import(/* webpackChunkName: "components__search-form-v2__README.md" */'/Users/hulongchao/Documents/code/2026/vite-playground/src/components/search-form-v2/README.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/hulongchao/Documents/code/2026/vite-playground/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
