// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/operation-group.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/operation-group.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/search-table.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/search-table.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/pro-table.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/pro-table.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/hulongchao/Documents/code/2026/vite-playground/docs/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/hulongchao/Documents/code/2026/vite-playground/src/components/search-form-v2/README.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/hulongchao/Documents/code/2026/vite-playground/src/components/search-form-v2/README.md?type=demo-index';

export const filesMeta = {
  'docs/components/operation-group': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/operation-group.md?type=text'),
  },
  'docs/components/search-table': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/search-table.md?type=text'),
  },
  'docs/components/pro-table': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/components/pro-table.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hulongchao/Documents/code/2026/vite-playground/docs/index.md?type=text'),
  },
  'components/search-form-v2/README': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__components" */'/Users/hulongchao/Documents/code/2026/vite-playground/src/components/search-form-v2/README.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
