// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/hulongchao/Documents/code/2026/vite-playground/node_modules/dumi/theme-default/builtins/Tree/index.js';
